app:
  domain: "sgp1.bytenut.cc"
  port: "3860"
  uuid: "3aa76bf6-a5ea-4646-96ab-70639804ba6f"
  xray-version: "25.10.15"
  hy2-version: "2.6.5"
  argo-version: "2025.10.0"
  argo-domain: "byte.noonehc.dpdns.org"
  argo-token: "eyJhIjoiOTk4YzJmYjJlNDEzYTVhZmExYzJlNGMyOGU3YTU5OTMiLCJ0IjoiZjllZDkyOTYtZThkMy00YjFmLTg3MDctMjBhOTBkOGNkNmZkIiwicyI6Ik1XRm1OMkZtTVdNdFlUVXlNUzAwTnpZd0xUbGpZMlV0T1Rjd05EVTVaRGRrTWpNMiJ9"
  remarks-prefix: ""
